name: tabular
description: Library for table formatting.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  #//sdk: '>=2.10.0 <3.0.0'

dependencies:
  # none

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
